// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBreedList() {
  return window['go']['main']['App']['GetBreedList']();
}

export function GetImageUrlByBreed(arg1) {
  return window['go']['main']['App']['GetImageUrlByBreed'](arg1);
}

export function GetRandomImageUrl() {
  return window['go']['main']['App']['GetRandomImageUrl']();
}
